# Generated by Django 4.0.1 on 2022-02-15 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mainpage', '0003_alter_costitems_name_alter_portals_member_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_b24', models.IntegerField(verbose_name='ID компании в Битрикс24')),
                ('number', models.CharField(max_length=10, verbose_name='Номер груза')),
                ('deal_id', models.IntegerField(verbose_name='ID сделки в Битрикс24')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.portals', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Груз',
                'verbose_name_plural': 'Грузы',
                'ordering': ['portal', 'deal_id'],
                'unique_together': {('id_b24', 'portal')},
            },
        ),
        migrations.CreateModel(
            name='CompaniesExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_b24', models.IntegerField(verbose_name='ID компании в Битрикс24')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование компании')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.portals', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['portal'],
                'unique_together': {('id_b24', 'portal')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_b24', models.IntegerField(verbose_name='ID сотрудника в Битрикс24')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.portals', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['portal'],
                'unique_together': {('id_b24', 'portal')},
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID услуги')),
                ('deal_id', models.IntegerField(verbose_name='ID сделки')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('type_cost', models.CharField(blank=True, choices=[('Наличный', 'Наличный')], max_length=50, null=True, verbose_name='Вид оплаты')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dealcard.cargo', verbose_name='Груз')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dealcard.companiesexpense', verbose_name='Компания')),
                ('cost_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='mainpage.costitems', verbose_name='Статья затрат')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee', to='dealcard.employee', verbose_name='Сотрудник')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner', to='dealcard.employee', verbose_name='Создатель')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.portals', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Затраты',
                'verbose_name_plural': 'Затраты',
                'ordering': ['update_date'],
            },
        ),
    ]
