# Generated by Django 4.0.1 on 2022-03-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Закрывающий документ'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='type_cost',
            field=models.CharField(blank=True, choices=[('Наличный (карты)', 'Наличный (карты)'), ('Расчетный счет', 'Расчетный счет'), ('В кассу', 'В кассу')], max_length=50, null=True, verbose_name='Вид оплаты'),
        ),
    ]
