# Generated by Django 4.0.1 on 2023-01-23 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealcard', '0002_expenses_document_alter_expenses_type_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='count',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Количество'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Документ'),
        ),
    ]
