# Generated by Django 4.1.1 on 2022-09-08 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealcard', '0002_expenses_document_alter_expenses_type_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Документ'),
        ),
    ]
