# Generated by Django 4.1.1 on 2023-01-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealcard', '0003_alter_expenses_document'),
        ('dealcard', '0003_expenses_count_expenses_price_and_more'),
    ]

    operations = [
    ]
