# Generated by Django 4.0.1 on 2023-02-04 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_alter_costitems_name_alter_portals_member_id_and_more'),
        ('dealcard', '0003_expenses_count_expenses_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.PositiveIntegerField(help_text='ID сделки из Битрикс24', verbose_name='ID сделки')),
                ('proceeds', models.DecimalField(blank=True, decimal_places=2, help_text='Сумма сделки', max_digits=12, null=True, verbose_name='Выручка')),
                ('sum_expenses', models.DecimalField(blank=True, decimal_places=2, help_text='Сумма затрат по сделке', max_digits=12, null=True, verbose_name='Затраты')),
                ('income', models.DecimalField(blank=True, decimal_places=2, help_text='Сумма прибыли по сделке', max_digits=12, null=True, verbose_name='Прибыль')),
                ('profitability', models.DecimalField(blank=True, decimal_places=2, help_text='Рентабельность сделки в процентах', max_digits=12, null=True, verbose_name='Рентабельность')),
                ('company_id', models.PositiveIntegerField(blank=True, help_text='ID компании сделки из Битрикс24', null=True, verbose_name='ID компании')),
                ('company_name', models.CharField(blank=True, help_text='Наименование компании сделки из Битрикс24', max_length=1024, null=True, verbose_name='Наименование компании')),
                ('manager_id', models.PositiveIntegerField(blank=True, help_text='ID менеджера сделки из Битрикс24', null=True, verbose_name='ID менеджера')),
                ('manager_name', models.CharField(blank=True, help_text='Имя менеджера сделки из Битрикс24', max_length=512, null=True, verbose_name='Менеджер')),
                ('closed', models.BooleanField(default=False, verbose_name='Сделка закрыта')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.portals', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Сделка',
                'verbose_name_plural': 'Сделки',
                'ordering': ['update_date'],
                'unique_together': {('deal_id', 'portal')},
            },
        ),
    ]
