# Generated by Django 4.1.1 on 2023-02-04 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dealcard', '0004_deal'),
        ('dealcard', '0004_merge_20230123_1408'),
    ]

    operations = [
    ]
