# Generated by Django 4.0.1 on 2023-02-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealcard', '0005_merge_0004_deal_0004_merge_20230123_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='start_date',
            field=models.DateField(blank=True, help_text='Дата создания сделки в Битрикс24', null=True, verbose_name='Дата создания сделки'),
        ),
    ]
