# Generated by Django 4.0.1 on 2022-02-02 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите наименование статьи затрат', max_length=200, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Статья затрат',
                'verbose_name_plural': 'Статьи затрат',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=255, verbose_name='Уникальный код портала')),
                ('url', models.URLField(max_length=255, verbose_name='Адрес портала')),
                ('name', models.CharField(max_length=255, verbose_name='Имя портала')),
            ],
            options={
                'verbose_name': 'Портал',
                'verbose_name_plural': 'Порталы',
            },
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(verbose_name='ID услуги')),
                ('deal_id', models.IntegerField(verbose_name='ID сделки')),
                ('expense', models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Сумма')),
                ('cargo_id', models.IntegerField(blank=True, null=True, verbose_name='ID груза')),
                ('cargo_number', models.CharField(blank=True, max_length=8, null=True, verbose_name='Номер груза')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Компания')),
                ('employee_id', models.IntegerField(blank=True, null=True, verbose_name='ID сотрудника')),
                ('employee_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО сотрудника')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('owner_id', models.IntegerField(verbose_name='ID пользователя')),
                ('owner_name', models.CharField(max_length=255, verbose_name='ФИО пользователя')),
                ('cost_item_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='mainpage.costitems', verbose_name='Статья затрат')),
                ('portal_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.portals', verbose_name='Портал')),
            ],
            options={
                'verbose_name': 'Затраты',
                'verbose_name_plural': 'Затраты',
                'ordering': ['update_date'],
            },
        ),
        migrations.AddField(
            model_name='costitems',
            name='portal_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.portals', verbose_name='Портал'),
        ),
    ]
