# Generated by Django 4.0.1 on 2022-02-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costitems',
            old_name='portal_id',
            new_name='portal',
        ),
    ]
