# Generated by Django 4.0.1 on 2022-02-15 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_rename_portal_id_costitems_portal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costitems',
            name='name',
            field=models.CharField(help_text='Введите наименование статьи затрат', max_length=200, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='portals',
            name='member_id',
            field=models.CharField(max_length=255, unique=True, verbose_name='Уникальный код портала'),
        ),
        migrations.AlterUniqueTogether(
            name='costitems',
            unique_together={('name', 'portal')},
        ),
    ]
